name: DEPLOY

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs
      env:
        GITHUB_PAT: ${{ secrets.TOKEN }}
